apiVersion: v1
kind: Secret
metadata:
  name: worker-node3-example-credentials
type: Opaque
data:
  username: ${BMC_NODE3_USERNAME}
  password: ${BMC_NODE3_PASSWORD}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker-node3-example
  labels:
    cluster-role: worker
    nodepool: nodepool-0
spec:
  online: true
  bootMACAddress: ${BMC_NODE3_MAC}
  bmc:
    address: ${BMC_NODE3_ADDRESS}
    disableCertificateVerification: true
    credentialsName: worker-node3-example-credentials
