apiVersion: v1
kind: Secret
metadata:
  name: worker-node2-example-credentials
type: Opaque
data:
  username: ${BMC_NODE2_USERNAME}
  password: ${BMC_NODE2_PASSWORD}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: worker-node2-example
  labels:
    cluster-role: worker
    nodepool: nodepool-0
spec:
  architecture: x86_64
  online: true
  bootMACAddress: ${BMC_NODE2_MAC}
  bmc:
    address: ${BMC_NODE2_ADDRESS}
    disableCertificateVerification: true
    credentialsName: worker-node2-example-credentials
